services:
  mongodb:
    image: mongo:7.0
    container_name: techmart-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: techmart2025
      MONGO_INITDB_DATABASE: techmart
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - techmart-network

  app:
    build: .
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - WEB_CONCURRENCY=8
      - MONGODB_URI=mongodb://admin:techmart2025@mongodb:27017/techmart?authSource=admin
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - techmart-network

volumes:
  mongodb_data:
    driver: local

networks:
  techmart-network:
    driver: bridge
