apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: mikadominguez/products-api:latest
          ports:
            - containerPort: 3003
          env:
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: DATABASE_URL
              value: mongodb://admin:techmart2025@mongodb:27017/products?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: products-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: mikadominguez/admin-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: DATABASE_URL
              value: mongodb://admin:techmart2025@mongodb:27017/admin?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: admin-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
        - name: client-api
          image: mikadominguez/client-api:latest
          ports:
            - containerPort: 3002
          env:
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: DATABASE_URL
              value: mongodb://admin:techmart2025@mongodb:27017/clients?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: client-api
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: client-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: mikadominguez/orders-api:latest
          ports:
            - containerPort: 3004
          env:
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: DATABASE_URL
              value: mongodb://admin:techmart2025@mongodb:27017/orders?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: orders-api